const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DATA_DIR=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data')),STORE=path.join(DATA_DIR,'store.json'),DEFAULT=path.join(ROOT,'data','default-store.json'),PUBLIC=path.join(ROOT,'public');
fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(STORE))fs.copyFileSync(DEFAULT,STORE);
const secret=String(process.env.JWT_SECRET||'dev-secret-change-me');
const read=()=>{try{return JSON.parse(fs.readFileSync(STORE,'utf8'))}catch{return JSON.parse(fs.readFileSync(DEFAULT,'utf8'))}};
const write=s=>{const t=STORE+'.tmp';fs.writeFileSync(t,JSON.stringify(s,null,2));fs.renameSync(t,STORE)};
const id=p=>p+'_'+Date.now().toString(36)+crypto.randomBytes(4).toString('hex');
const b64=o=>Buffer.from(JSON.stringify(o)).toString('base64url');
const sign=p=>crypto.createHmac('sha256',secret).update(p).digest('base64url');
const token=u=>{const p=b64({id:u.id,email:u.email,role:u.role,name:u.name,exp:Date.now()+180*864e5});return p+'.'+sign(p)};
const verify=t=>{if(!t||!t.includes('.'))return null;const[p,s]=t.split('.');if(!crypto.timingSafeEqual(Buffer.from(sign(p)),Buffer.from(s)))return null;const d=JSON.parse(Buffer.from(p,'base64url'));return d.exp>Date.now()?d:null};
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');const h=crypto.scryptSync(p,salt,64).toString('hex');return salt+':'+h};
const check=(p,v)=>{try{const[s,h]=v.split(':');return crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(p,s,64).toString('hex')),Buffer.from(h))}catch{return false}};
function ensureAdmin(){const s=read(),email=String(process.env.ADMIN_EMAIL||'admin@rsrshop.com').toLowerCase(),pw=String(process.env.ADMIN_PASSWORD||'Admin123!');let a=s.users.find(x=>x.role==='admin');if(!a){a={id:id('usr'),name:'RSR Administrator',email,passwordHash:hash(pw),role:'admin',createdAt:new Date().toISOString()};s.users.push(a)}else{a.email=email;if(process.env.ADMIN_PASSWORD)a.passwordHash=hash(pw)}write(s)}ensureAdmin();
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const body=req=>new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>8e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)});
const auth=req=>verify((req.headers.authorization||'').replace(/^Bearer\s+/i,''));
const safe=u=>{const{passwordHash,...x}=u;return x};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json','.json':'application/json','.svg':'image/svg+xml'};
async function api(req,res,u){
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,version:'19.0.0'});
 if(req.method==='GET'&&u.pathname==='/api/config'){const s=read().settings;return json(res,200,{...s,shopName:process.env.SHOP_NAME||s.shopName,contactEmail:process.env.CONTACT_EMAIL||'',contactPhone:process.env.CONTACT_PHONE||'',facebookUrl:process.env.FACEBOOK_URL||''})}
 if(req.method==='POST'&&u.pathname==='/api/auth/register'){const d=await body(req),name=String(d.name||'').trim(),email=String(d.email||'').trim().toLowerCase(),pw=String(d.password||'');if(name.length<2||!email.includes('@')||pw.length<6)return json(res,400,{error:'Enter a valid name, email, and password of at least 6 characters.'});const s=read();if(s.users.some(x=>x.email===email))return json(res,409,{error:'That email is already registered. Use Sign In.'});const user={id:id('usr'),name,email,passwordHash:hash(pw),role:'customer',createdAt:new Date().toISOString()};s.users.push(user);write(s);return json(res,201,{token:token(user),user:safe(user)})}
 if(req.method==='POST'&&u.pathname==='/api/auth/login'){const d=await body(req),email=String(d.email||'').trim().toLowerCase(),pw=String(d.password||'');const s=read(),user=s.users.find(x=>x.email===email);if(!user||!check(pw,user.passwordHash))return json(res,401,{error:'Incorrect email or password.'});return json(res,200,{token:token(user),user:safe(user)})}
 const a=auth(req);if(u.pathname.startsWith('/api/')&&!a)return json(res,401,{error:'Please sign in again.'});
 if(req.method==='GET'&&u.pathname==='/api/me'){const s=read();let user=s.users.find(x=>x.id===a.id);if(!user){user={id:a.id,name:a.name,email:a.email,passwordHash:'',role:a.role,createdAt:new Date().toISOString(),restored:true};s.users.push(user);write(s)}return json(res,200,{user:safe(user)})}
 if(req.method==='GET'&&u.pathname==='/api/orders'){const s=read(),orders=a.role==='admin'?s.orders:s.orders.filter(x=>x.userId===a.id);return json(res,200,{orders:orders.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt))})}
 if(req.method==='POST'&&u.pathname==='/api/orders'){const d=await body(req),amount=Number(d.robuxAmount);if(!d.method||!d.robloxUsername||!amount||!d.paymentMethod||!d.receiptData)return json(res,400,{error:'Complete all fields and upload a receipt.'});const s=read(),rate=Number(s.settings.rates[d.method]||0),order={id:id('ord'),orderNo:'RSR-'+Date.now().toString().slice(-8),userId:a.id,customerName:a.name,method:d.method,robloxUsername:String(d.robloxUsername),robuxAmount:amount,totalPhp:Math.round(amount*rate*100)/100,paymentMethod:d.paymentMethod,receiptData:d.receiptData,status:'Pending Review',createdAt:new Date().toISOString(),adminNote:''};s.orders.push(order);write(s);return json(res,201,{order})}
 if(req.method==='PATCH'&&u.pathname.startsWith('/api/admin/orders/')){if(a.role!=='admin')return json(res,403,{error:'Admin only.'});const oid=u.pathname.split('/').pop(),d=await body(req),s=read(),o=s.orders.find(x=>x.id===oid);if(!o)return json(res,404,{error:'Order not found.'});if(d.status)o.status=d.status;if(typeof d.adminNote==='string')o.adminNote=d.adminNote;write(s);return json(res,200,{order:o})}
 if(req.method==='GET'&&u.pathname==='/api/chat'){const s=read();return json(res,200,{messages:a.role==='admin'?s.messages:s.messages.filter(x=>x.userId===a.id)})}
 if(req.method==='POST'&&u.pathname==='/api/chat'){const d=await body(req),text=String(d.text||'').trim();if(!text)return json(res,400,{error:'Type a message.'});const s=read(),m={id:id('msg'),userId:a.role==='admin'?String(d.userId||''):a.id,senderRole:a.role,senderName:a.name,text,createdAt:new Date().toISOString()};s.messages.push(m);write(s);return json(res,201,{message:m})}
 return json(res,404,{error:'Not found'});
}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u);let p=u.pathname==='/'?'/index.html':u.pathname;p=path.normalize(p).replace(/^\.\.(\/|\\|$)/,'');const f=path.join(PUBLIC,p);if(!f.startsWith(PUBLIC)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','cache-control':p.includes('sw.js')?'no-cache':'public, max-age=300'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);json(res,500,{error:'Server error'})}});
server.listen(PORT,()=>console.log(`RSR Shop V19 running on ${PORT}`));
